version: "3"
services:
  module-m2:
    build: ./sw-backend-module-m2
    restart: always
    image: ac3e/wys-module-m2:1
    ports:
        - "8082:8082"
    depends_on:
      - "db"
    environment: 
        DB_USER: "wys"
        DB_PASSWORD: "rac3e/07"
        DB_IP_ADDRESS: "db"
        DB_PORT: "3306"
        DB_SCHEMA: "wys"
        SPACES_MODULE_IP: "module-space"
        SPACES_MODULE_PORT: "8083"
        SPACES_MODULE_API_CREATE: "/api/spaces/create"
        PROJECTS_MODULE_HOST: "module-project"
        PROJECTS_MODULE_PORT: "8081"
        PROJECTS_MODULE_API: "/api/projects/"
  
  module-filestorage:
    build: ./sw-backend-module-filestorage
    restart: always
    image: ac3e/wys-module-filestorage:1
    ports:
        - "8085:8085"
    volumes:
      - filestorage-volume:/app/data/
    environment: 
        FS_LOCATION_PATH: "/app/data/"
        FS_DNS_URL: 'http://wysapi.ac3eplatforms.com'
  
  module-layout:
    build: ./sw-backend-module-layout
    restart: always
    image: ac3e/wys-module-layout:1
    ports:
      - "8086:8086"
      environment:
      DB_USER: "wys"
      DB_PASSWORD: "rac3e/07"
      DB_IP_ADDRESS: "db"
      DB_PORT: "3306"
      DB_SCHEMA: "wys"
      BUILDINGS_MODULE_HOST: "module-building"
      BUILDINGS_MODULE_PORT: "8084"
      BUILDINGS_MODULE_API_LOCS: "/api/buildings/locations/"
      SPACES_MODULE_HOST: "module-space"
      SPACES_MODULE_PORT: "8083"
      SPACES_MODULE_API_CREATE: "/api/spaces/create"
      PROJECTS_MODULE_HOST: "module-project"
      PROJECTS_MODULE_PORT: "8081"
      PROJECTS_MODULE_API: "/api/projects/"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"


  module-project:
    build: ./sw-backend-module-project
    restart: always
    image: ac3e/wys-module-project:1
    ports:
        - "8081:8081"
    depends_on:
      - "db"
    environment: 
        DB_USER: "wys"
        DB_PASSWORD: "rac3e/07"
        DB_IP_ADDRESS: "db"
        DB_PORT: "3306"
        DB_SCHEMA: "wys"
        BUILDINGS_MODULE_HOST: "module-building"
        BUILDINGS_MODULE_PORT: "8084"
        BUILDINGS_MODULE_API_LOCS_GET: "/api/buildings/locations/"
  
  module-building:
    build: ./sw-backend-module-building
    restart: always
    image: ac3e/wys-module-building:1
    ports:
        - "8084:8084"
    depends_on:
      - "db"
    environment: 
        DB_USER: "wys"
        DB_PASSWORD: "rac3e/07"
        DB_IP_ADDRESS: "db"
        DB_PORT: "3306"
        DB_SCHEMA: "wys"
        PROJECTS_MODULE_API: "/api/projects/"
        PROJECTS_MODULE_HOST: "module-project"
        PROJECTS_MODULE_PORT: "8081"

  
  module-space:
    build: ./sw-backend-module-space
    restart: always
    image: ac3e/wys-module-space:1
    ports:
        - "8083:8083"
    depends_on:
      - "db"
    environment: 
        DB_USER: "wys"
        DB_PASSWORD: "rac3e/07"
        DB_IP_ADDRESS: "db"
        DB_PORT: "3306"
        DB_SCHEMA: "wys"
  
  redis:
    image: redis
    restart: "always"
    ports: 
        - 6379:6379
  
  module-layout-worker:
    build: 
      context: ./sw-backend-module-layout
      dockerfile: Dockerfile-worker
    image: ac3e/worker:1
    restart: always
    environment: 
        REDIS_URL: "redis://redis:6379"
        

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'wys'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'wys'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'rac3e/07'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rac3e/07'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
  filestorage-volume:  
